FROM maven:3.8.2-jdk-11 AS BUILD_MAVEN3_JAVA11_IMAGE
WORKDIR /build
COPY . /build/
RUN mvn clean package


FROM openjdk:11-jre
WORKDIR /app/
COPY --from=BUILD_MAVEN3_JAVA11_IMAGE /build/target/boot-met-swaggger-service-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java","-jar","boot-met-swaggger-service-0.0.1-SNAPSHOT.jar"]